-- Select role.
USE ROLE SYSADMIN;

-- Select warehouse.
-- USE WAREHOUSE COMPUTE_WH;

-- Use database.
USE DATABASE EDW_TEST;

--
CREATE OR REPLACE SCHEMA EDW_TEST.TEST_DEPLOYMENT;

-- Create or replace TEST_DEPLOYMENT_TABLE table.
CREATE OR REPLACE TABLE EDW_TEST.TEST_DEPLOYMENT.TEST_DEPLOYMENT_TABLE(
DEPLOYMENT_NAME VARCHAR(255)
);

-- Add a new column to the  TEST_DEPLOYMENT_TABLE table.
ALTER TABLE EDW_TEST.TEST_DEPLOYMENT.TEST_DEPLOYMENT_TABLE ADD COLUMN DEPLOYMENT_STATUS VARCHAR(255);

-- Grant usage on SCHEMA EDW_TEST.TEST_DEPLOYMENT to the JDAO_ADMIN role.
GRANT USAGE ON SCHEMA EDW_TEST.TEST_DEPLOYMENT TO ROLE JDAO_ADMIN;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA EDW_TEST.TEST_DEPLOYMENT TO ROLE JDAO_ADMIN;

-- Grant ownership on PACTS360_INT schema to the JDAO_ADMIN role.
-- GRANT OWNERSHIP ON SCHEMA EDW_TEST.TEST_DEPLOYMENT TO ROLE JDAO_ADMIN;

-- Drop table.
DROP TABLE EDW_TEST.TEST_DEPLOYMENT.TEST_DEPLOYMENT_TABLE;

-- Drop schema.
-- DROP SCHEMA EDW_TEST.TEST_DEPLOYMENT;
